/**
 * `@usequeek/app-sdk` — the shared kit every Queek app is built from.
 *
 * Queek speaks Standard Webhooks (`webhook-id`, `webhook-timestamp`,
 * `webhook-signature` over `{id}.{timestamp}.{raw body}`, keyed by the
 * decoded `whsec_…` bytes) on two channels: the install handoff (signed
 * with the APP secret) and topic deliveries (signed with the
 * PER-INSTALLATION endpoint secret). The Merchant API takes the
 * installation credential as `X-Client-Key`.
 */

export {
  API_KEY_EXPIRED_CODE,
  API_KEY_REVOKED_CODE,
  APP_INSTALLATION_GONE_CODE,
  APP_INSTALLATION_PENDING_CODE,
  APP_JWT_SKEW_SECONDS,
  APP_JWT_TTL_SECONDS,
  APP_PRIVATE_KEY_FORMS,
  APP_TOKEN_REVOKED_CODE,
  type AppCredential,
  AppMintHaltedError,
  decodePrivateKeyInput,
  INSUFFICIENT_SCOPE_CODE,
  INVALID_CLIENT_CODE,
  INVALID_CLIENT_KEY_CODE,
  InvalidAppCredentialError,
  isAppTokenRevoked,
  isInstallationGone,
  isInstallationPending,
  isInsufficientScope,
  isInvalidClient,
  isResyncCooldown,
  isTokenRefusal,
  loadAppCredential,
  MAX_MINT_ATTEMPTS,
  MINT_BACKOFF_BASE_MS,
  MINT_BACKOFF_MAX_MS,
  RESYNC_COOLDOWN_CODE,
  RETRY_JITTER_MAX_MS,
  type SignAppJwtOptions,
  signAppJwt,
  TOKEN_VALIDITY_SKEW_SECONDS,
  TOO_MANY_REQUESTS_CODE,
  UnknownInstallationError,
} from "./app-auth.js";
export {
  type AuthFetchOptions,
  BRIDGE_TOKEN_TIMEOUT_MS,
  type InstalledAuth,
  installAuthFetch,
  LAUNCH_TOKEN_PARAM,
  readLaunchToken,
  stripLaunchToken,
} from "./auth-fetch.js";
export {
  backgroundTaskCount,
  type CatchupFailure,
  type CatchupInstallation,
  type CatchupOptions,
  type CatchupResult,
  type DetachOptions,
  detach,
  runInstallationCatchup,
} from "./background.js";
export {
  apiHostsFromEnv,
  createQueekClient,
  DEFAULT_API_HOSTS,
  devApiHostsFromEnv,
  InvalidApiBaseError,
  isWriteMethod,
  MERCHANT_API_PATH,
  type MerchantPaths,
  newIdempotencyKey,
  type OperationResponse,
  QueekApiError,
  type QueekClient,
  type QueekClientOptions,
  type QueekErrorDetails,
  queekApiErrorFromResponse,
  type RequestOptions,
  type RetryOptions,
  resolveApiBase,
  type StoreProfile,
} from "./client.js";
export {
  type AlertBody,
  type AlertSeverity,
  type CollectedDefinition,
  type CollectedDefinitionCreate,
  type CollectedDefinitionUpdate,
  type CollectedField,
  collectedDefinitions,
  createRecord,
  type MerchantAlert,
  type SetupNotice,
  type SetupNoticeBody,
  type SetupNoticeItem,
  type SetupNoticeStatus,
  type SuccessEnvelope,
  sendAlert,
  setSetupNotice,
} from "./collected.js";
export {
  decryptSecret,
  encryptSecret,
  parseStoreKey,
  storeKeyFingerprint,
} from "./crypto.js";
export {
  type CoreDelivery,
  type CoreHeaders,
  type DeliveryResult,
  decodeBody,
  type InstallDelivery,
  readHeader,
} from "./delivery.js";
export {
  APP_SOURCE,
  type AppInboundMessage,
  type AppOutboundMessage,
  BRIDGE_VERSION,
  type BridgeTheme,
  buildReadyMessage,
  capText,
  clipOutbound,
  DASHBOARD_SOURCE,
  type EmbedEvent,
  type EmbedEventTarget,
  type EmbedPostTarget,
  type FrameBridgeOptions,
  isAllowedImageUrl,
  isAllowedOpenTarget,
  listenToDashboard,
  MAX_ACTION_ID_LENGTH,
  MAX_CAPABILITIES,
  MAX_CAPABILITY_LENGTH,
  MAX_FILTER_LENGTH,
  MAX_HEADING_LENGTH,
  MAX_IMAGE_URL_LENGTH,
  MAX_LABEL_LENGTH,
  MAX_LOCALE_LENGTH,
  MAX_PATH_LENGTH,
  MAX_PICKED_ITEMS,
  MAX_REQUEST_ID_LENGTH,
  MAX_RESIZE_HEIGHT,
  MAX_RESOURCE_TITLE_LENGTH,
  MAX_SDK_VERSION_LENGTH,
  MAX_SECONDARY_ACTIONS,
  MAX_SELECTION_ID_LENGTH,
  MAX_SELECTION_IDS,
  MAX_TARGET_LENGTH,
  MAX_TOAST_DURATION_MS,
  MAX_TOAST_LENGTH,
  type PickResourceRequest,
  parseInboundMessage,
  parseOutboundMessage,
  type ReadyOptions,
  type ResourceItem,
  type SaveBarAction,
  type SaveBarState,
  sendAck,
  sendBridgeMessage,
  sendNavigated,
  sendOpen,
  sendPickResource,
  sendReady,
  sendResize,
  sendSaveBar,
  sendTitle,
  sendToast,
  type ThemeMode,
  type TitleActionDef,
  type TitleActionTone,
  type ToastTone,
} from "./frame.js";
export {
  type HandoffEnvelope,
  type HandoffEnvelopeAny,
  type HandoffInstallationRef,
  type HandoffStore,
  INSTALL_EVENT,
  type InstallData,
  type InstallEnvelope,
  RESYNC_EVENT,
  type ResyncEnvelope,
  SETTINGS_EVENT,
  type SettingsData,
  type SettingsEnvelope,
  UNINSTALL_EVENT,
  type UninstallData,
  type UninstallEnvelope,
} from "./handoff.js";
export {
  buildInstallationRecord,
  handleInstallDelivery,
  handleInstallRequest,
  type InstallCallbacks,
  type InstallHandlerOptions,
  installationScopesEqual,
  saveResyncedInstallation,
} from "./install-handlers.js";
export {
  createLogger,
  type LogFields,
  type Logger,
  type LoggerOptions,
  type LogLevel,
  REDACTED,
} from "./logger.js";
export {
  buildProxyCanonicalString,
  handleProxyRequest,
  PROXY_CUSTOMER_PARAM,
  PROXY_KID_PARAM,
  PROXY_MAX_SKEW_SECONDS,
  PROXY_NONCE_PARAM,
  PROXY_SHOP_PARAM,
  PROXY_SIGNATURE_PARAM,
  PROXY_TIMESTAMP_PARAM,
  type ProxyFailure,
  type ProxyQuery,
  type ProxyRequestOptions,
  type ProxyResponder,
  type ProxyStoreOptions,
  type ProxyVerification,
  type ProxyVerifyOptions,
  signProxyQuery,
  verifyProxyDelivery,
  verifyProxyQuery,
  verifyProxyQueryDetailed,
} from "./proxy.js";
export {
  type ResyncListItem,
  type ResyncOptions,
  type ResyncResult,
  resyncFromQueek,
} from "./resync.js";
export {
  MAX_TIMESTAMP_SKEW_SECONDS,
  SECRET_PREFIX,
  type SignatureFailure,
  type SignatureInput,
  secretKeyBytes,
  signQueekPayload,
  type VerifyOptions,
  verifyQueekSignature,
  verifyQueekSignatureDetailed,
  WEBHOOK_ID_HEADER,
  WEBHOOK_SIGNATURE_HEADER,
  WEBHOOK_TIMESTAMP_HEADER,
} from "./signatures.js";
export {
  createInstallationStore,
  createPostgresPool,
  defaultClearCachedTokenIfMatches,
  INSTALLATION_SCHEMA_VERSION,
  type InstallationRecord,
  type InstallationStore,
  type InstallationStoreSelector,
  PostgresInstallationStore,
  type PostgresStoreOptions,
  SqliteInstallationStore,
  type SqliteStoreOptions,
  type WebhookSecretCandidate,
} from "./store.js";
export {
  applyTheme,
  getThemeModeFromUrl,
  installThemeListener,
  rememberThemeMode,
  THEME_PARAM,
  THEME_STORAGE_KEY,
  type ThemeDocument,
  type ThemeDocumentElement,
  type ThemeListenerOptions,
  type ThemeStorage,
  themeBootstrapScript,
} from "./theme.js";
export {
  APP_API_PATH,
  AppTokenProvider,
  type AppTokens,
  createAppTokenProvider,
  createInstallationClient,
  type InstallationClientOptions,
  mintPath,
  resolveAppApiBase,
  type TokenProviderOptions,
} from "./tokens.js";
export {
  handleWebhookDelivery,
  handleWebhookRequest,
  QUEEK_TOPIC_HEADER,
  type QueekWebhookEnvelope,
  type SecretResolution,
  type WebhookHandlerContext,
  type WebhookHandlerFn,
  type WebhookHandlerOptions,
} from "./webhooks.js";
